#!/bin/bash

#Initializing Git
git init 

#Creating 10 files and committing all of them by looping
for i in {1..10};

do
    touch "f$i"
    git add "f$i"
    git commit -m "This is commit number $i"
done

#Finding the hash value of root commit
root=$(git rev-list --max-parents=0 HEAD)

#Finding the hash value of current commit
commit=$(git rev-parse HEAD)

for j in {1..10};
do 
    if [ $commit != $root ]
    then 
        parent=$(git rev-parse "$commit~")
        branch=$(git rev-parse --short "$commit")
        echo "========================================================================"
        git checkout -b "$branch"
        echo -e "Creating branch at $commit\n"
        commit=$parent
    fi
done