#!/bin/bash


#########################################################################
#                       Iterative Shell Script                          #
#########################################################################


#Initializing Git
git init 

#Creating 10 files and committing all of them by looping
for i in {1..10};
do

    touch "f$i"
    git add "f$i"
    git commit -m "This is commit number $i"

done


#creating branch at every ancestor of last commit 
for i in {1..9};
do 

    parent=$(git rev-parse "HEAD~$i")
    branch=$(git rev-parse --short "HEAD~$i")
    echo "========================================================================"
    git branch "$branch" "$parent"
    echo -e "Creating branch at $parent\n"

done