#!/bin/bash

#Initializing Git
git init 

#Creating 10 files and committing all of them by looping
for i in {1..10};

do
    touch "f$i"
    git add "f$i"
    git commit -m "This is commit number $i"
done

#Finding the hash value of root commit
root=$(git rev-list --max-parents=0 HEAD)

#Finding the hash value of current commit
current_hash=$(git rev-parse HEAD)

#Making a recursive function and creating branches on every ancestor of last commit.
#function definition
create_branches() {
    if [ $1 != $root ]
    then 
        current_hash=$1
        parent=$(git rev-parse "$current_hash^")
        branch=$(git rev-parse --short "$current_hash^")
        echo "========================================================================"
        git checkout $parent
        git branch "$branch"
        echo -e "Creating branch at ancestor of $current_hash\n"
        create_branches "$parent"
    fi 
}

#function call
create_branches "$current_hash"

#checking out to master again
git checkout master 
